In [16]:
import numpy as np

data = np.arange(16 * 1024, dtype=np.uint8)
key = np.arange(8, dtype=np.uint8)

data

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)

In [17]:
%%time

from convbc import ebc
cipher_text = ebc.encrypt(data, key)

CPU times: user 1.13 s, sys: 26.4 ms, total: 1.16 s
Wall time: 1.14 s


In [18]:
print(cipher_text)

[212 139 250 ... 143 203 180]


In [19]:
%%time

from convbc import ebc
plain_text = ebc.decrypt(cipher_text, key)

CPU times: user 1.09 s, sys: 7.2 ms, total: 1.1 s
Wall time: 1.08 s


In [20]:
plain_text

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)