In [16]:
import numpy as np

data = np.arange(16 * 1024, dtype=np.uint8)
key = np.arange(8, dtype=np.uint8)

data

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)

In [17]:
%%time

from convbc import cbc
cipher_text = cbc.encrypt(data, key)

CPU times: user 1.73 s, sys: 881 ms, total: 2.62 s
Wall time: 2.59 s


In [18]:
cipher_text

array([ 94,  35, 123, ...,   5, 204, 155], dtype=uint8)

In [19]:
%%time

from convbc import cbc
plain_text = cbc.decrypt(cipher_text, key)

CPU times: user 1.14 s, sys: 22.7 ms, total: 1.16 s
Wall time: 1.14 s


In [20]:
plain_text

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)