In [1]:
import numpy as np

data = np.arange(16 * 1024, dtype=np.uint8)
key = np.arange(8, dtype=np.uint8)

data

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)

In [2]:
%%time

from convbc import ctr
cipher_text = ctr.encrypt(data, key)

CPU times: user 1.16 s, sys: 51.6 ms, total: 1.21 s
Wall time: 1.17 s


In [3]:
cipher_text

array([191, 155, 125, ..., 167, 138,  78], dtype=uint8)

In [4]:
%%time

from convbc import ctr
plain_text = ctr.decrypt(cipher_text, key)

CPU times: user 1.08 s, sys: 5.82 ms, total: 1.08 s
Wall time: 1.07 s


In [5]:
plain_text

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)