In [16]:
import numpy as np

data = np.arange(16 * 1024, dtype=np.uint8)
key = np.arange(8, dtype=np.uint8)

data

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)

In [17]:
%%time

from convbc import ctr
cipher_text = ctr.encrypt(data, key)

CPU times: user 1.09 s, sys: 16.3 ms, total: 1.11 s
Wall time: 1.09 s


In [18]:
cipher_text

array([191, 155, 125, ..., 167, 138,  78], dtype=uint8)

In [19]:
%%time

from convbc import ctr
plain_text = ctr.decrypt(cipher_text, key)

CPU times: user 1.21 s, sys: 13.5 ms, total: 1.23 s
Wall time: 1.22 s


In [20]:
plain_text

array([  0,   1,   2, ..., 253, 254, 255], dtype=uint8)